// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using event_booking.Data;

#nullable disable

namespace event_booking.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            /*modelBuilder.Entity("EventEventUser", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("EventUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EventId", "EventUserId");

                    b.ToTable("EventEventUser");
                });

            modelBuilder.Entity("EventUserOrganizer", b =>
                {
                    b.Property<string>("EventUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.HasKey("EventUserId", "OrganizerId");

                    b.ToTable("EventUserOrganizer");
                });

            modelBuilder.Entity("EventUserVenue", b =>
                {
                    b.Property<string>("EventUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventUserId", "VenueId");

                    b.ToTable("EventUserVenue");
                });*/

            modelBuilder.Entity("JunctionTicketVip", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("TicketID");

                    b.Property<int>("VipId")
                        .HasColumnType("int")
                        .HasColumnName("VIP_ID");

                    b.HasKey("TicketId", "VipId");

                    b.HasIndex(new[] { "VipId" }, "IX_Junction_Ticket_VIP_VIP_ID");

                    b.ToTable("Junction_Ticket_VIP", "evnt");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            //Tables
            /*modelBuilder.Entity("TicketVip", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("VipId")
                        .HasColumnType("int");

                    b.HasKey("TicketId", "VipId");

                    b.ToTable("TicketVip");
                });*/

            modelBuilder.Entity("UserEventFollow", b =>
                {
                    b.Property<string>("EventUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EventUserID");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    b.HasKey("EventUserId", "EventId");

                    b.HasIndex(new[] { "EventId" }, "IX_User_Event_Follow_EventID");

                    b.ToTable("User_Event_Follow", "evnt");
                });

            modelBuilder.Entity("UserOrganizerFollow", b =>
                {
                    b.Property<string>("EventUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EventUserID");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizerID");

                    b.HasKey("EventUserId", "OrganizerId");

                    b.HasIndex(new[] { "OrganizerId" }, "IX_User_Organizer_Follow_OrganizerID");

                    b.ToTable("User_Organizer_Follow", "evnt");
                });

            modelBuilder.Entity("UserVenueFollow", b =>
                {
                    b.Property<string>("EventUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EventUserID");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("VenueID");

                    b.HasKey("EventUserId", "VenueId");

                    b.HasIndex(new[] { "VenueId" }, "IX_User_Venue_Follow_VenueID");

                    b.ToTable("User_Venue_Follow", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DiscountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<string>("DiscountName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PriceMultiplier")
                        .HasColumnType("int");

                    b.HasKey("DiscountId")
                        .HasName("PK_TicketPricing");

                    b.ToTable("Discount", "evnt", t =>
                        {
                            t.HasComment("Ticket Pricing Information");
                        });
                });

            modelBuilder.Entity("event_booking.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("EarlyBirdCutoff")
                        .HasColumnType("date");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("date");

                    b.Property<int>("EventCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("EventCategoryID");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizerID");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("date");

                    b.HasKey("EventId");

                    b.HasIndex(new[] { "EventCategoryId" }, "IX_Events_EventCategoryID");

                    b.HasIndex(new[] { "OrganizerId" }, "IX_Events_OrganizerID");

                    b.ToTable("Events", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.EventCategory", b =>
                {
                    b.Property<int>("EventCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EventCategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EventCategoryId");

                    b.ToTable("EventCategories", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.EventUser", b =>
                {
                    b.Property<string>("EventUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EventUserID");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Document")
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Picture")
                        .HasMaxLength(450)
                        .IsUnicode(false)
                        .HasColumnType("varchar(450)");

                    b.HasKey("EventUserId");

                    b.ToTable("EventUser", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.GroupDiscount", b =>
                {
                    b.Property<int>("GroupDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GroupDiscountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupDiscountId"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MinimumAdults")
                        .HasColumnType("int");

                    b.Property<int>("MinimumChildren")
                        .HasColumnType("int");

                    b.Property<int>("PriceMultiplier")
                        .HasColumnType("int");

                    b.HasKey("GroupDiscountId");

                    b.ToTable("GroupDiscounts", "evnt", t =>
                        {
                            t.HasComment("Discounts on groups");
                        });
                });

            modelBuilder.Entity("event_booking.Models.Loyalty", b =>
                {
                    b.Property<string>("EventUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EventUserID");

                    b.Property<int?>("PriceMultiplier")
                        .HasColumnType("int");

                    b.Property<int?>("TicketCount")
                        .HasColumnType("int");

                    b.HasKey("EventUserId");

                    b.ToTable("Loyalty", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.Organizer", b =>
                {
                    b.Property<int>("OrganizerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrganizerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizerId"));

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("OrganizerCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("OrganizerCategoryID");

                    b.HasKey("OrganizerId")
                        .HasName("PK_Organizers");

                    b.HasIndex(new[] { "OrganizerCategoryId" }, "IX_Organizers_OrganizerCategoryID");

                    b.ToTable("Organizers", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.OrganizerCategory", b =>
                {
                    b.Property<int>("OrganizerCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrganizerCategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizerCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrganizerCategoryId")
                        .HasName("PK_OrganizerCategories");

                    b.ToTable("OrganizerCategories", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PurchaseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.HasKey("PurchaseId");

                    b.ToTable("Purchase", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<string>("EventUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EventUserID");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseID");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("date");

                    b.Property<int?>("SalePrice")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex(new[] { "EventUserId" }, "IX_Sales_EventUserID");

                    b.HasIndex(new[] { "PurchaseId" }, "IX_Sales_PurchaseID");

                    b.ToTable("Sales", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SeatID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("VenueID")
                        .HasComment("Seats Information");

                    b.HasKey("SeatId");

                    b.HasIndex(new[] { "SectionId" }, "IX_Seats_SectionID");

                    b.HasIndex(new[] { "VenueId" }, "IX_Seats_VenueID");

                    b.ToTable("Seats", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SectionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<int>("PriceMultiplier")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SectionId");

                    b.ToTable("Section", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TicketID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("BasePrice")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int")
                        .HasColumnName("DiscountID");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    b.Property<string>("EventUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EventUserID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseID");

                    b.Property<int>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("SeatID");

                    b.Property<int?>("TicketPrice")
                        .HasColumnType("int");

                    b.Property<int?>("TicketTypeId")
                        .HasColumnType("int")
                        .HasColumnName("TicketTypeID");

                    b.Property<int>("VenueId")
                        .HasColumnType("int")
                        .HasColumnName("VenueID");

                    b.HasKey("TicketId");

                    b.HasIndex(new[] { "DiscountId" }, "IX_Tickets_DiscountID");

                    b.HasIndex(new[] { "EventUserId" }, "IX_Tickets_EventUserID");

                    b.HasIndex(new[] { "PurchaseId" }, "IX_Tickets_PurchaseID");

                    b.HasIndex(new[] { "SeatId" }, "IX_Tickets_SeatID");

                    b.HasIndex(new[] { "TicketTypeId" }, "IX_Tickets_TicketTypeID");

                    b.HasIndex(new[] { "VenueId" }, "IX_Tickets_VenueID");

                    b.HasIndex(new[] { "EventId", "SeatId" }, "Ticket_Unique_Index")
                        .IsUnique();

                    b.ToTable("Tickets", "evnt", t =>
                        {
                            t.HasComment("Event Tickets");
                        });
                });

            modelBuilder.Entity("event_booking.Models.TicketGroup", b =>
                {
                    b.Property<int>("TicketGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TicketGroupID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketGroupId"));

                    b.Property<int?>("GroupDiscountId")
                        .HasColumnType("int")
                        .HasColumnName("GroupDiscountID");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int")
                        .HasColumnName("PurchaseID");

                    b.HasKey("TicketGroupId");

                    b.HasIndex(new[] { "GroupDiscountId" }, "IX_TicketGroup_GroupDiscountID");

                    b.HasIndex(new[] { "PurchaseId" }, "IX_TicketGroup_PurchaseID");

                    b.ToTable("TicketGroup", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.TicketType", b =>
                {
                    b.Property<int>("TicketTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TicketTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketTypeId"));

                    b.Property<int>("PriceMultiplier")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TicketTypeId")
                        .HasName("PK_UserFollows");

                    b.ToTable("TicketType", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VenueID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SeatCapacity")
                        .HasColumnType("int")
                        .HasColumnName("Seat Capacity");

                    b.HasKey("VenueId");

                    b.ToTable("Venue", "evnt");
                });

            modelBuilder.Entity("event_booking.Models.Vip", b =>
                {
                    b.Property<int>("VipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VIP_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VipId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("EventID");

                    b.Property<string>("VipName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("VIP_Name");

                    b.Property<int>("VipPrice")
                        .HasColumnType("int")
                        .HasColumnName("VIP_Price");

                    b.HasKey("VipId")
                        .HasName("PK_VIPAccess");

                    b.HasIndex(new[] { "EventId" }, "IX_VIP_EventID");

                    b.HasIndex(new[] { "VipId", "EventId" }, "VIP_Unique_Index")
                        .IsUnique();

                    b.ToTable("VIP", "evnt", t =>
                        {
                            t.HasComment("VIP Area");
                        });
                });

            //Relationships
            modelBuilder.Entity("JunctionTicketVip", b =>
                {
                    b.HasOne("event_booking.Models.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_Junction_Ticket_VIP_Tickets");

                    b.HasOne("event_booking.Models.Vip", null)
                        .WithMany()
                        .HasForeignKey("VipId")
                        .IsRequired()
                        .HasConstraintName("FK_Junction_Ticket_VIP_VIP");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserEventFollow", b =>
                {
                    b.HasOne("event_booking.Models.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Event_Follow_Events_1");

                    b.HasOne("event_booking.Models.EventUser", null)
                        .WithMany()
                        .HasForeignKey("EventUserId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Event_Follow_EventUser");
                });

            modelBuilder.Entity("UserOrganizerFollow", b =>
                {
                    b.HasOne("event_booking.Models.EventUser", null)
                        .WithMany()
                        .HasForeignKey("EventUserId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Organizer_Follow_EventUser");

                    b.HasOne("event_booking.Models.Organizer", null)
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Organizer_Follow_Organizers_1");
                });

            modelBuilder.Entity("UserVenueFollow", b =>
                {
                    b.HasOne("event_booking.Models.EventUser", null)
                        .WithMany()
                        .HasForeignKey("EventUserId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Venue_Follow_EventUser");

                    b.HasOne("event_booking.Models.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Venue_Follow_Venue_1");
                });

            modelBuilder.Entity("event_booking.Models.Event", b =>
                {
                    b.HasOne("event_booking.Models.EventCategory", "EventCategory")
                        .WithMany("Events")
                        .HasForeignKey("EventCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Events_EventCategories");

                    b.HasOne("event_booking.Models.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .IsRequired()
                        .HasConstraintName("FK_Events_Organizers");

                    b.Navigation("EventCategory");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("event_booking.Models.EventUser", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithOne()
                        .HasForeignKey("event_booking.Models.EventUser", "EventUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("event_booking.Models.Loyalty", b =>
                {
                    b.HasOne("event_booking.Models.EventUser", "EventUser")
                        .WithOne("Loyalty")
                        .HasForeignKey("event_booking.Models.Loyalty", "EventUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Loyalty_EventUser");

                    b.Navigation("EventUser");
                });

            modelBuilder.Entity("event_booking.Models.Organizer", b =>
                {
                    b.HasOne("event_booking.Models.OrganizerCategory", "OrganizerCategory")
                        .WithMany("Organizers")
                        .HasForeignKey("OrganizerCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Organizers_OrganizerCategories");

                    b.Navigation("OrganizerCategory");
                });

            modelBuilder.Entity("event_booking.Models.Sale", b =>
                {
                    b.HasOne("event_booking.Models.EventUser", "EventUser")
                        .WithMany("Sales")
                        .HasForeignKey("EventUserId")
                        .HasConstraintName("FK_Sales_EventUser");

                    b.HasOne("event_booking.Models.Purchase", "Purchase")
                        .WithMany("Sales")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK_Sales_Purchase_1");

                    b.Navigation("EventUser");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("event_booking.Models.Seat", b =>
                {
                    b.HasOne("event_booking.Models.Section", "Section")
                        .WithMany("Seats")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_Seats_Section");

                    b.HasOne("event_booking.Models.Venue", "Venue")
                        .WithMany("Seats")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_Seats_Venue");

                    b.Navigation("Section");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("event_booking.Models.Ticket", b =>
                {
                    b.HasOne("event_booking.Models.Discount", "Discount")
                        .WithMany("Tickets")
                        .HasForeignKey("DiscountId")
                        .HasConstraintName("FK_Tickets_Discount_4");

                    b.HasOne("event_booking.Models.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Events");

                    b.HasOne("event_booking.Models.EventUser", "EventUser")
                        .WithMany("Tickets")
                        .HasForeignKey("EventUserId")
                        .HasConstraintName("FK_Tickets_EventUser_3");

                    b.HasOne("event_booking.Models.Purchase", "Purchase")
                        .WithMany("Tickets")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK_Tickets_Purchase_6");

                    b.HasOne("event_booking.Models.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Seats_2");

                    b.HasOne("event_booking.Models.TicketType", "TicketType")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketTypeId")
                        .HasConstraintName("FK_Tickets_TicketType_5");

                    b.HasOne("event_booking.Models.Venue", "Venue")
                        .WithMany("Tickets")
                        .HasForeignKey("VenueId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Venue_1");

                    b.Navigation("Discount");

                    b.Navigation("Event");

                    b.Navigation("EventUser");

                    b.Navigation("Purchase");

                    b.Navigation("Seat");

                    b.Navigation("TicketType");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("event_booking.Models.TicketGroup", b =>
                {
                    b.HasOne("event_booking.Models.GroupDiscount", "GroupDiscount")
                        .WithMany("TicketGroups")
                        .HasForeignKey("GroupDiscountId")
                        .HasConstraintName("FK_TicketGroup_GroupDiscounts_1");

                    b.HasOne("event_booking.Models.Purchase", "Purchase")
                        .WithMany("TicketGroups")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("FK_TicketGroup_Purchase");

                    b.Navigation("GroupDiscount");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("event_booking.Models.Vip", b =>
                {
                    b.HasOne("event_booking.Models.Event", "Event")
                        .WithMany("Vips")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK_VIP_Events");

                    b.Navigation("Event");
                });

            //Navigations
            modelBuilder.Entity("event_booking.Models.Discount", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("event_booking.Models.Event", b =>
                {
                    b.Navigation("Tickets");

                    b.Navigation("Vips");
                });

            modelBuilder.Entity("event_booking.Models.EventCategory", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("event_booking.Models.EventUser", b =>
                {
                    b.Navigation("Loyalty");

                    b.Navigation("Sales");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("event_booking.Models.GroupDiscount", b =>
                {
                    b.Navigation("TicketGroups");
                });

            modelBuilder.Entity("event_booking.Models.Organizer", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("event_booking.Models.OrganizerCategory", b =>
                {
                    b.Navigation("Organizers");
                });

            modelBuilder.Entity("event_booking.Models.Purchase", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("TicketGroups");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("event_booking.Models.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("event_booking.Models.Section", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("event_booking.Models.TicketType", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("event_booking.Models.Venue", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
